# Generated by Django 5.2.6 on 2025-11-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_distribuidor', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Distribuidor')),
                ('tipo_servicio', models.CharField(choices=[('LOCAL', 'Local'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('tiempo_entrega_dias', models.IntegerField(verbose_name='Tiempo de Entrega (días)')),
                ('comision', models.DecimalField(decimal_places=2, help_text='Comisión en porcentaje', max_digits=5)),
                ('ultima_revision', models.DateField(auto_now=True, verbose_name='Última Revisión')),
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
                'ordering': ['nombre_distribuidor'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Empresa')),
                ('contacto_principal', models.CharField(max_length=100, verbose_name='Contacto Principal')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Código')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField(verbose_name='Stock Actual')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('distribuidores', models.ManyToManyField(related_name='productos_distribuidos', to='app_Proveedor.distribuidor', verbose_name='Distribuidores')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_suministrados', to='app_Proveedor.proveedor', verbose_name='ID Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
