# Generated by Django 5.1 on 2025-11-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del Producto'),
        ),
    ]
