# Generated by Django 5.1 on 2025-11-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Proveedor', '0002_alter_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto/Cargo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mensual')),
                ('edad', models.IntegerField(verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
    ]
