# Generated by Django 5.1 on 2025-11-13 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Proveedor', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50, verbose_name='Estado del Envío')),
                ('pais', models.CharField(max_length=50, verbose_name='País de Destino')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección de Destino')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_Proveedor.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Vendida')),
                ('fecha_venta', models.DateField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_Proveedor.cliente', verbose_name='Cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_Proveedor.producto', verbose_name='Producto Vendido')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
